### Muhammad Abdul Nafay
### 19P-0117

#### Question
In this assignment your task is to:
1. Write a program (strictly in python) that receives initial state (use abstraction) as input 
by the user.  
2. The program first determines if the goal state is reachable. If not, then it should simply 
display an unreachable message and exit. 
3. If goal is reachable then it should be able to generate and display next states and choose 
an action until the goal state is found. 
4. The choice of action from the queue should be done using Iterative Deepening Search 
Algorithm.
5. The program should use tree data structure and maintain and display a frontier (queue) 
of the search tree.
6. At  the  end  of  the  program  when  the  goal  state  is  found  it  should  display  the  total  path 
cost of the search process.

In [47]:
import numpy as np
from copy import deepcopy

In [48]:
class Node:
    def __init__(self, data, parent=None):
        self.left = None
        self.right = None
        self.down = None
        self.up = None
        self.data = data
        self.parent = parent

    def __str__(self):
        return str(self.data)

class Tree:
    def __init__(self, data):
        self.state = Node(data)

In [49]:
class puzzle_11:
    def __init__(self, init_matrix, goal_matrix):
        self.init_matrix = Node(init_matrix)
        self.goal_matrix = Node(goal_matrix)

    def get_initialState(self):
        self.init_matrix = np.array([[1, 5, 2, 3], [4, 6, 10, 7], [8, 9, 0, 11]])  # 0 is the empty space
        # self.init_matrix = np.array([[0, 9, 8, 1], [4, 5, 6, 7], [2, 3, 10, 11]]) # 0 is the empty space
        return self.init_matrix

    def get_initialState_User(self, init_matrix):
        entries = list(map(int, input().split()))
        # For printing the matrix
        self.init_matrix = np.array(entries).reshape(3, 4)

    def get_GoalState(self):
        self.goal_matrix = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
        return self.goal_matrix

    def get_GoalState_User(self, goal_matrix):
        entries = list(map(int, input().split()))
        # For printing the matrix
        self.goal_matrix = np.array(entries).reshape(3, 4)

    def get_matrix(self, init_matrix):
        print(self.init_matrix)

    def check_goalReached(self, init_matrix, goal_matrix):
        print("Goal Reached!")
        return (np.array_equal(init_matrix, goal_matrix))

    def swapPositions(self, board, X_init, Y_init, X_final, Y_final):
        temp = deepcopy(board)
        temp_data = temp[X_init][Y_init]
        temp[X_init][Y_init] = temp[X_final][Y_final]
        temp[X_final][Y_final] = temp_data
        return temp

        #Operations
    def Up(self, node):
        index = np.where(node.data == 0)
        X, Y = index
        X, Y = int(X), int(Y)
        # print("0 is at: index",X, Y)
        if(X == 0):
            print("Up operation cant be performed")
            return Node(None)
        else:
            print("Performing UP")
            temp = self.swapPositions(node.data, X, Y, X-1, Y)
            return Node(temp, parent=node)

    def Down(self, node):
        index = np.where(node.data == 0)
        X, Y = index
        X, Y = int(X), int(Y)
        # print("0 is at: index",X, Y)
        if(X == 2):
            print("Down operation cant be performed")
            return Node(None)
        else:
            print("Performing Down")
            temp = self.swapPositions(node.data, X, Y, X+1, Y)
            return Node(temp, parent=node)

    def Left(self, node):
        index = np.where(node.data == 0)
        X, Y = index
        X, Y = int(X), int(Y)
        # print("0 is at: index",X, Y)
        if(Y == 0):
            print("Left operation cant be performed")
            return Node(None)
        else:
            print("Performing Left")
            temp = self.swapPositions(node.data, X, Y, X, Y-1)
            return Node(temp, parent=node)

    def Right(self, node):
        index = np.where(node.data == 0)
        X, Y = index
        X, Y = int(X), int(Y)
        # print("0 is at: index",X, Y)
        if(Y == 2):
            print("Right operation cant be performed")
            return Node(None)
        else:
            print("Performing Right")
            temp = self.swapPositions(node.data, X, Y, X, Y+1)
            return Node(temp, parent=node)

    def solvibility(self, mat):#Checking Whether the given state is solvible or not.
        #calculating inversion count of init_matrix
        InversionCount_init = 0
        for i in range(len(mat)):
            for j in range(len(mat[0])):
                X = mat[i][j]
                # print("X: ", X, "(I | J): ", i, j)
                if(X == 0):
                    continue
                # print("Inversion Count: ", InversionCount_init)
                for w in range(len(mat)):
                    for k in range(len(mat[0])):
                        if(w < i):
                            continue
                        elif(w == i):
                            if(k <= j):
                                continue
                            else:
                                if(X > mat[w][k] and mat[w][k] != 0):
                                    InversionCount_init = InversionCount_init + 1
                        elif(w > i):
                            if(X > mat[w][k] and mat[w][k] != 0):
                                InversionCount_init = InversionCount_init + 1

        # print("Initial State: \n", self.init_matrix)
        print("Inversion Count: ", InversionCount_init)

        if(InversionCount_init % 2 == 0):
            print("Even, Hence Solvable!")
            return True
        else:
            print("Odd, Hence NOT Solvable!")
            return False

In [50]:

def get_children(node):
    node.left = obj.Left(node)
    node.right = obj.Right(node)
    node.down = obj.Down(node)
    node.up = obj.Up(node)


def print_queue(node):
    print("[")
    for item in node:
        print(item, end="\n")
    print("\n]")


In [51]:
class IDFS:
    def __init__(self, init, goal):
        self.start = Tree(init)
        self.goal = Node(goal)
        self.q = []
        self.visited = []
        self.goal_found = False
        self.final = None
        

    def get_child_queue(self, node):
        if(node.up.data is not None and node.up not in self.visited):
            self.q.append(node.up)
            self.visited.append(node.up)
        if(node.down.data is not None and node.down not in self.visited):
            self.q.append(node.down)
            self.visited.append(node.down)
        if(node.right.data is not None and node.right not in self.visited):
            self.q.append(node.right)
            self.visited.append(node.right)
        if(node.left.data is not None and node.left not in self.visited):
            self.q.append(node.left)
            self.visited.append(node.left)

    def execute(self):
        if(obj.solvibility(self.start.state.data)):
            depth = 0
            while(not self.goal_found):
                print("Depth =", depth)
                self.q = []
                self.q.append(self.start.state)
                self.search(depth)
                if(not self.goal_found):
                    print("============DEPTH INCREASING===========")
                depth += 1
        else:
            print("Goal Unreachable.")

    #Depth First Search
    def search(self, depth, curr_depth=0):
        if(self.goal_found):
            return
        curr = self.q[-1]
        print("Current State: ")
        print(curr, end="\n\n")

        #Goal Test
        if(np.array_equal(curr.data, self.goal.data)):
            self.goal_found = True
            self.final = curr
            self.path_cost = curr_depth
        else:
            print("Queue: ")
            print_queue(self.q)
            if(depth == curr_depth):
                return
            get_children(curr)
            self.get_child_queue(curr)

            curr_depth += 1
            while(self.q[-1] != curr):
                self.search(depth, curr_depth)
                if(self.goal_found):
                    return
                self.q.remove(self.q[-1])

            curr_depth -= 1

In [52]:
init_matrix = np.array([]) #Initial State
goal_matrix = np.array([]) #Goal State
obj = puzzle_11(init_matrix, goal_matrix)

init_matrix = obj.get_initialState()
goal_matrix = obj.get_GoalState()

print("Initial State: \n", init_matrix)
print("Goal State: \n", goal_matrix)

puzzle = IDFS(init_matrix, goal_matrix)
puzzle.execute()

#Finds the path from goal node to start node using parent pointers
if(puzzle.goal_found):
    x = puzzle.final
    path_list = []
    while(x is not None):
        path_list.insert(0, x)
        x = x.parent

    print("Final Path  = ")
    print_queue(path_list)
    print("Total Path Cost =", puzzle.path_cost)


Initial State: 
 [[ 1  5  2  3]
 [ 4  6 10  7]
 [ 8  9  0 11]]
Goal State: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Inversion Count:  6
Even, Hence Solvable!
Depth = 0
Current State: 
[[ 1  5  2  3]
 [ 4  6 10  7]
 [ 8  9  0 11]]

Queue: 
[
[[ 1  5  2  3]
 [ 4  6 10  7]
 [ 8  9  0 11]]

]
============DEPTH INCREASING===========
Depth = 1
Current State: 
[[ 1  5  2  3]
 [ 4  6 10  7]
 [ 8  9  0 11]]

Queue: 
[
[[ 1  5  2  3]
 [ 4  6 10  7]
 [ 8  9  0 11]]

]
Performing Left
Right operation cant be performed
Down operation cant be performed
Performing UP
Current State: 
[[ 1  5  2  3]
 [ 4  6 10  7]
 [ 8  0  9 11]]

Queue: 
[
[[ 1  5  2  3]
 [ 4  6 10  7]
 [ 8  9  0 11]]
[[ 1  5  2  3]
 [ 4  6  0  7]
 [ 8  9 10 11]]
[[ 1  5  2  3]
 [ 4  6 10  7]
 [ 8  0  9 11]]

]
Current State: 
[[ 1  5  2  3]
 [ 4  6  0  7]
 [ 8  9 10 11]]

Queue: 
[
[[ 1  5  2  3]
 [ 4  6 10  7]
 [ 8  9  0 11]]
[[ 1  5  2  3]
 [ 4  6  0  7]
 [ 8  9 10 11]]

]
============DEPTH INCREASING===========
Depth = 2
Cu