In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.8.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11501568/11490434 [==============================] - 2s 0us/step


In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])


In [5]:
predictions = model(x_train[:1]).numpy()
predictions


array([[ 0.03530468, -0.01627076,  0.11026955,  0.13003539,  0.31741548,
        -0.22631438,  0.6480367 , -1.0355611 , -0.87028867, -0.40339357]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()


array([[0.10570795, 0.10039422, 0.11393692, 0.11621138, 0.14016089,
        0.08137443, 0.19508047, 0.03622735, 0.04273793, 0.06816845]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [8]:
loss_fn(y_train[:1], predictions).numpy()


2.5086942

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [10]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2961 - accuracy: 0.9133
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1401 - accuracy: 0.9584
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1063 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0874 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0736 - accuracy: 0.9772


In [11]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 0s - loss: 0.0736 - accuracy: 0.9776 - 439ms/epoch - 1ms/step


[0.07360568642616272, 0.9775999784469604]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])


In [13]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.0198327e-07, 2.8665440e-08, 2.3887585e-05, 3.7057724e-04,
        1.9644223e-12, 2.2461225e-07, 1.4673488e-13, 9.9960250e-01,
        1.1173112e-07, 2.5157672e-06],
       [5.0895721e-07, 1.0219715e-05, 9.9998569e-01, 1.5843640e-06,
        2.6406447e-14, 1.0577445e-06, 8.5298603e-07, 2.4207399e-13,
        1.3584305e-07, 3.5373427e-14],
       [9.0108578e-08, 9.9976867e-01, 3.4379238e-05, 8.0470210e-07,
        7.4243540e-06, 5.5482160e-06, 6.7160827e-06, 1.4671056e-04,
        2.9387900e-05, 1.8188412e-07],
       [9.9997437e-01, 2.8521514e-08, 5.4878396e-06, 6.4368450e-08,
        1.1837741e-08, 1.2749585e-07, 1.1570565e-05, 3.9077017e-06,
        1.2135512e-08, 4.4457902e-06],
       [1.0572623e-05, 1.1677568e-08, 3.1176139e-06, 3.2934214e-08,
        9.9896133e-01, 1.6714341e-07, 1.6679820e-05, 1.1079977e-04,
        6.9983571e-07, 8.9656923e-04]], dtype=float32)>